// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA784yuPX8Cc3gRh2vfS3FmbAB4nN4jSdc',
    appId: '1:789792568803:web:d4218048751882ad9e1cd6',
    messagingSenderId: '789792568803',
    projectId: 'smart-notebook-5f2b9',
    authDomain: 'smart-notebook-5f2b9.firebaseapp.com',
    storageBucket: 'smart-notebook-5f2b9.firebasestorage.app',
    measurementId: 'G-7NLFFR3MHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy-MZ2KFVFyqnx3BXHca9oSkJfSlovI9I',
    appId: '1:789792568803:android:da5cf606bd67b8899e1cd6',
    messagingSenderId: '789792568803',
    projectId: 'smart-notebook-5f2b9',
    storageBucket: 'smart-notebook-5f2b9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoqKTmjr-QemAU4EicF5hP6e7VhplVuW0',
    appId: '1:789792568803:ios:b89fc4712e3a154c9e1cd6',
    messagingSenderId: '789792568803',
    projectId: 'smart-notebook-5f2b9',
    storageBucket: 'smart-notebook-5f2b9.firebasestorage.app',
    iosClientId: '789792568803-j86s52ognqgdl5m7oudf3mrqsm18mvcj.apps.googleusercontent.com',
    iosBundleId: 'com.example.notebookApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoqKTmjr-QemAU4EicF5hP6e7VhplVuW0',
    appId: '1:789792568803:ios:b89fc4712e3a154c9e1cd6',
    messagingSenderId: '789792568803',
    projectId: 'smart-notebook-5f2b9',
    storageBucket: 'smart-notebook-5f2b9.firebasestorage.app',
    iosClientId: '789792568803-j86s52ognqgdl5m7oudf3mrqsm18mvcj.apps.googleusercontent.com',
    iosBundleId: 'com.example.notebookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA784yuPX8Cc3gRh2vfS3FmbAB4nN4jSdc',
    appId: '1:789792568803:web:57231d46a13ef8889e1cd6',
    messagingSenderId: '789792568803',
    projectId: 'smart-notebook-5f2b9',
    authDomain: 'smart-notebook-5f2b9.firebaseapp.com',
    storageBucket: 'smart-notebook-5f2b9.firebasestorage.app',
    measurementId: 'G-3Q0X2PHKVX',
  );
}
